name: Deploy_to_cloud_run

on:
  push:
    branches:
      - main

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  serviceAccount: ${{ secrets.GCP_SA_KEY }}

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # - name: Setup GCP Service Account
      #   id: gcloud
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     version: 'latest'
      #     service_account_email: ${{ secrets.GCP_SA_EMAIL }}
      #     service_account: ${{ secrets.GCP_SA }}
          # export_default_credentials: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Authenticate GCP
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_NAME }} --key-file=PARSE_JSON(${{ secrets.GCP_CREDENTIALS }})

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/betting-api:latest .
      # - name: Test Docker image
      #   run: |
      #       docker run gcr.io/${{ secrets.GCP_PROJECT_ID }}/betting-api:latest sh -c "pytest" 
      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/betting-api:latest
      - name: Deploy
        run: |
          gcloud run deploy betting-api \
          --region europe-west1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/betting-api \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}